name: 📊 Coverage
run-name: 📊 ${{ inputs.service }} • Coverage Analysis

on:
  workflow_call:
    inputs:
      blocking:
        required: true
        type: boolean
      service:
        required: true
        type: string

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Contextual Coverage Log
        run: |
          echo "Running coverage for ${{ inputs.service }} (commit ${{ github.sha }})"
      - name: Placeholder for JaCoCo coverage
        run: echo "status=success" >> $GITHUB_OUTPUT
