name: Deploy (Reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service:
        required: true
        type: string
    secrets: inherit

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      argo_env: ${{ steps.env.outputs.env }}
    steps:
      - id: env
        run: echo "env=${{ inputs.environment }}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: [prepare]
    environment: ${{ inputs.environment }}
    steps:
      - name: Placeholder for Helm + ArgoCD sync
        run: echo "Deploying ${{ inputs.service }} to ${{ needs.prepare.outputs.argo_env }}"
