name: 🚀 Deploy
run-name: 🚀 ${{ inputs.service }} • ${{ inputs.environment }} Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Log Context
        run: |
          echo "Deploying ${{ inputs.service }} to ${{ inputs.environment }}"
          echo "Commit: ${{ github.sha }}"
          echo "Triggered by: ${{ github.actor }}"
      - name: Placeholder for Helm + ArgoCD sync
        run: echo "Argo sync for ${{ inputs.service }} to ${{ inputs.environment }}"
