name: Develop Validation Pipeline

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
    secrets: inherit

env:
  SERVICE: ${{ inputs.service }}
  COMMIT_SHA: ${{ github.event.client_payload.sha || github.sha }}

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    with:
      blocking: true
      service: ${{ env.SERVICE }}

  coverage:
    needs: tests
    uses: ./.github/workflows/coverage.yml
    with:
      blocking: true
      service: ${{ env.SERVICE }}

  lint:
    needs: coverage
    uses: ./.github/workflows/lint.yml
    with:
      blocking: true
      service: ${{ env.SERVICE }}
