name: 🧪 Feature & Hotfix Pipeline
run-name: 🧪 ${{ inputs.service }}@${{ github.ref_name }} • Feature/Hotfix

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      sha:
        required: true
        type: string

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    with:
      blocking: false
      service: ${{ inputs.service }}
      sha: ${{ inputs.sha }}

    secrets: inherit
