name: Feature & Hotfix Pipeline

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    with:
      blocking: false
      service: ${{ inputs.service }}
    secrets: inherit
