name: 🐳 Build & Push Quarkus Service
run-name: 🐳 ${{ inputs.service }} • Docker Build & Push

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      sha:
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Log Context
        run: |
          echo "🐳 Building Quarkus service for: ${{ inputs.service }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "Workflow Repository: ${{ github.repository }}"
          echo "Target Commit: ${{ inputs.sha }}"

      # ----------------------------------------------
      # 🔽 CHECKOUT TARGET SERVICE
      # ----------------------------------------------
      - name: 📦 Checkout target service code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.service }}
          ref: ${{ inputs.sha }}
          token: ${{ secrets.CI_DISPATCH_TOKEN }}

      # ----------------------------------------------
      # ☕ SETUP ENVIRONMENT
      # ----------------------------------------------
      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build Quarkus JAR
        run: ./gradlew build -x test

      - name: Docker Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          IMAGE=ghcr.io/${{ inputs.service }}:${{ inputs.sha }}
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          echo "Building image: $IMAGE"
          docker build -t "$IMAGE" .
          echo "Pushing image: $IMAGE"
          docker push "$IMAGE"

      - name: Build Summary
        run: echo "✅ Quarkus service ${{ inputs.service }} built and pushed to GHCR successfully."
