name: 🧱 Validation Pipeline
run-name: 🧱 ${{ inputs.service }} • Validation

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    with:
      blocking: true
      service: ${{ inputs.service }}
    secrets: inherit

  coverage:
    needs: tests
    uses: ./.github/workflows/coverage.yml
    with:
      blocking: true
      service: ${{ inputs.service }}
    secrets: inherit

  lint:
    needs: coverage
    uses: ./.github/workflows/lint.yml
    with:
      blocking: true
      service: ${{ inputs.service }}
    secrets: inherit
