name: Staging Deployment Pipeline

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      service: ${{ inputs.service }}
    secrets: inherit
