name: Run Tests (Reusable)

on:
  workflow_call:
    inputs:
      blocking:
        required: true
        type: boolean
      service:
        required: true
        type: string
    secrets: inherit

jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: ${{ !inputs.blocking }}
    outputs:
      result: ${{ steps.result.outputs.status }}
    steps:
      - name: Placeholder for actual test steps
        id: result
        run: echo "status=success" >> $GITHUB_OUTPUT
