name: 🧪 Tests
run-name: 🧪 ${{ inputs.service }} • Test Stage

on:
  workflow_call:
    inputs:
      blocking:
        required: true
        type: boolean
      service:
        required: true
        type: string
      sha:
        required: true
        type: string

jobs:
  tests:
    name: 🧪 Run Tests for ${{ inputs.service }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ !inputs.blocking }}

    steps:
      - name: 🧾 Log Context
        run: |
          echo "🧪 Running tests for: ${{ inputs.service }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "Workflow Repository: ${{ github.repository }}"
          echo "Target Commit: ${{ inputs.sha }}"

      # ----------------------------------------------
      # 🔽 CHECKOUT TARGET SERVICE REPOSITORY
      # ----------------------------------------------
      - name: 📦 Checkout target service code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.service }}
          ref: ${{ inputs.sha }}
          token: ${{ secrets.CI_DISPATCH_TOKEN }}

      # ----------------------------------------------
      # 🧰 SETUP BUILD ENVIRONMENT
      # ----------------------------------------------
      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # ----------------------------------------------
      # 🧱 Install dependencies
      # ----------------------------------------------
      - name: 🧱 Install dependencies (Gradle)
        if: hashFiles('build.gradle*') != ''
        run: ./gradlew clean assemble --no-daemon

      # ----------------------------------------------
      # 🧪 RUN TESTS
      # ----------------------------------------------
      - name: 🧪 Run Gradle Tests
        if: hashFiles('build.gradle*') != ''
        run: ./gradlew test --no-daemon --stacktrace

      # ----------------------------------------------
      # 📦 UPLOAD TEST RESULTS (optional, visible in central CI)
      # ----------------------------------------------
      - name: 📤 Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ inputs.service }}
          path: |
            target/surefire-reports/**
            build/test-results/**
          if-no-files-found: ignore
